openapi: 3.0.0
info:
  title: Global Database API
  version: 1.0.0
  description: API documentation for the Global Database Plugin
servers:
  - url: http://localhost:5003
paths:
  /search:
    get:
      summary: Search the Global Database
      parameters:
        - name: query
          in: query
          description: The search query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful search
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: string

  /company/{id}:
    get:
      summary: Get company information
      parameters:
        - name: id
          in: path
          description: The ID of the company
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful fetch
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  industry:
                    type: string
                  location:
                    type: string
                  revenue:
                    type: string
                  employee_count:
                    type: string
